version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: jonaselasticsearch
    restart: always
    ports:
      - "39200:9200"
      - "39300:9300"
    environment:
      - CLUSTER_NAME=jonaselasticsearchcluster
      - NODE_NAME=elasticsearch1
      - CORS_ENABLED = true
      - XPACK_GRAPH_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    networks:
      - elkstack

  kibana:
    image: crauwjo/elkstack:kibana1.0
    container_name: jonaskibana
    restart: always
    ports:
      - "35601:5601"
    environment:
      - XPACK_GRAPH_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    networks:
      - elkstack

networks:
  elkstack:
    driver: bridge

volumes:
  elkstack:
