version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    container_name: jonaselasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - CLUSTER_NAME=jonaselasticsearchcluster
      - NODE_NAME=elasticsearch1
      - CORS_ENABLED = true
      - XPACK_GRAPH_ENABLED=true
      - XPACK_MONITORING_ENABLED=true
      - XPACK_REPORTING_ENABLED=true
      - XPACK_SECURITY_ENABLED=true
    networks:
      - elkstack
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  logstash:
    image: logstash:latest
    container_name: jonaslogstash
    environment:
      - CONFIG_PATH=/usr/share/logstash/config/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elkstack
    volumes:
      - ./data/logstash/config:/usr/share/logstash/config
      - ./data/logstash/pipeline:/usr/share/logstash/pipeline

  kibana:
    image: crauwjo/elkstack:kibana1.0
    container_name: jonaskibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - XPACK_GRAPH_ENABLED=true
      - XPACK_MONITORING_ENABLED=true
      - XPACK_REPORTING_ENABLED=true
      - XPACK_SECURITY_ENABLED=true
    networks:
      - elkstack

networks:
  elkstack:
    driver: bridge

volumes:
  elkstack:
